//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.05 at 05:39:28 AM SAST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soapwebservice.example.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.soapwebservice.interfaces;
